### ISSUE TITLE
TYPO3 Exception: #1203584729: "" is not a valid cache identifier

### ISSUE THREAD

**Issue by DavidBruchmann** [georgringer/news#1301]
## Bug Report

**Current Behavior**
adding a proxy-class according to the news-manual in some situations an exception is triggered and then making the whole backend unusable, I still never found out what exactly to do, for making the backend usable again, just deleting cache-files is not sufficient.
I had the situation that everything was running like expected and after using composer to update an extension (gridelements) the error was triggered.
The backend is in detail unusable because the error-message copied to the bottom is triggered. In essence there is an array into `TYPO3\CMS\Core\Cache\CacheManager->cacheConfigurations`  integrated that has no key and the whole $cacheConfigurations-array looks like this:
```
$cacheConfigurations => array(17 items)
      core => array(4 items)
      hash => array(4 items)
      pages => array(4 items)
      pagesection => array(4 items)
      runtime => array(4 items)
      rootline => array(4 items)
      imagesizes => array(4 items)
      assets => array(4 items)
      l10n => array(4 items)
      fluid_template => array(3 items)
      extbase => array(4 items)
      adminpanel_requestcache => array(empty)
      rx_shariff => array(4 items)
      news => array(4 items)
      '' => array(1 item)
          groups => array(2 items)
             0 => 'pages' (5 chars)
             1 => 'all' (3 chars)
      static_info_tables => array(3 items)
      news_category => array(1 item)
```
That means that the array for news itself is correct but afterwards is a wrong array added for some reason.

**Expected behavior/output**
Usually no ghost entries should be automatically added to CacheManager->cacheConfigurations.
Primary I'm interested in publishing my extension without having to expect that  it breaks complete installations.

**Environment**
- TYPO3 version(s): 10.4.4
- news version: 8.3.0
- Composer Mode: yes
- OS: Windows 10

**Possible Solution**
Changing one line in `CacheManager::createAllCaches()` solves the issue in my case, but that's in the core:
```
            if (!isset($this->caches[$identifier])) {
                $this->createCache($identifier);
            }
```
to this:
```
            if ($identifier && !isset($this->caches[$identifier])) {
                $this->createCache($identifier);
            }
```

**Additional context**
I made a copy of the cached news-folder when it was still working like expected and found that there wasn't yet the cached class inside.  
After the composer-update of the extension gridelements the backend was unusable and the class did exist in the cache-folder,

backtrace on error:
```
Tue, 16 Jun 2020 03:52:04 +0700 [CRITICAL] request="86bbe5e9f6085" component="TYPO3.CMS.Core.Error.DebugExceptionHandler":
 Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1203584729: "" is not a valid cache identifier. | 
 InvalidArgumentException thrown in file \typo3\sysext\core\Classes\Cache\Frontend\AbstractFrontend.php in line 50. 
 Requested URL: http://localhost/typo3/index.php?route=%2Frecord%2Fedit&token=--AnonymizedToken--&edit%5Btx_news_domain_model_news%5D%5B2%5D=edit&returnUrl=%2Ftypo3%2Findex.php%3Froute%3D%252Fmodule%252Fweb%252Flist%26token%3De1ed94f1fd1d83996b592fa54595359245076768%26id%3D44
 - {"TYPO3_MODE":"BE","exception":"InvalidArgumentException: \"\" is not a valid cache identifier. 
 in \\typo3\\sysext\\core\\Classes\\Cache\\Frontend\\AbstractFrontend.php:50\nStack trace:
  #0 \\typo3\\sysext\\core\\Classes\\Cache\\CacheManager.php(345): TYPO3\\CMS\\Core\\Cache\\Frontend\\AbstractFrontend->__construct('', Object(TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend))
  #1 \\typo3\\sysext\\core\\Classes\\Cache\\CacheManager.php(284): TYPO3\\CMS\\Core\\Cache\\CacheManager->createCache('')
  #2 \\typo3\\sysext\\core\\Classes\\Cache\\CacheManager.php(215): TYPO3\\CMS\\Core\\Cache\\CacheManager->createAllCaches()
  #3 \\typo3conf\\ext\\news\\Classes\\Hooks\\DataHandler.php(42): TYPO3\\CMS\\Core\\Cache\\CacheManager->flushCachesInGroupByTag('pages', 'tx_news_uid_2')
  #4 [internal function]: GeorgRinger\\News\\Hooks\\DataHandler->clearCachePostProc(Array, Object(TYPO3\\CMS\\Core\\DataHandling\\DataHandler))
  #5 \\typo3\\sysext\\core\\Classes\\Utility\\GeneralUtility.php(3325): call_user_func_array(Array, Array)
  #6 \\typo3\\sysext\\core\\Classes\\DataHandling\\DataHandler.php(8219): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::callUserFunction('GeorgRinger\\\\New...', Array, Object(TYPO3\\CMS\\Core\\DataHandling\\DataHandler))
  #7 \\typo3\\sysext\\core\\Classes\\DataHandling\\DataHandler.php(8063): TYPO3\\CMS\\Core\\DataHandling\\DataHandler->prepareCacheFlush('tx_news_domain_...', 2, 44)
  #8 \\typo3\\sysext\\core\\Classes\\DataHandling\\DataHandler.php(1241): TYPO3\\CMS\\Core\\DataHandling\\DataHandler->processClearCacheQueue()
  #9 \\typo3\\sysext\\backend\\Classes\\Controller\\EditDocumentController.php(562): TYPO3\\CMS\\Core\\DataHandling\\DataHandler->process_datamap()
  #10 \\typo3\\sysext\\backend\\Classes\\Controller\\EditDocumentController.php(426): TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->processData(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #11 [internal function]: TYPO3\\CMS\\Backend\\Controller\\EditDocumentController->mainAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #12 \\typo3\\sysext\\backend\\Classes\\Http\\RouteDispatcher.php(66): call_user_func_array(Array, Array)
  #13 \\typo3\\sysext\\backend\\Classes\\Http\\RequestHandler.php(94): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #14 \\typo3\\sysext\\extbase\\Classes\\Middleware\\SignalSlotDeprecator.php(49): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #15 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Extbase\\Middleware\\SignalSlotDeprecator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))
  #16 \\typo3\\sysext\\backend\\Classes\\Middleware\\SiteResolver.php(69): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #17 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #18 \\typo3\\sysext\\backend\\Classes\\Middleware\\AdditionalResponseHeaders.php(41): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #19 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #20 \\typo3\\sysext\\backend\\Classes\\Middleware\\OutputCompression.php(47): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #21 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #22 \\typo3\\sysext\\backend\\Classes\\Middleware\\BackendUserAuthenticator.php(77): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #23 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #24 \\typo3\\sysext\\backend\\Classes\\Middleware\\BackendRouteInitialization.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #25 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #26 \\typo3\\sysext\\backend\\Classes\\Middleware\\ForcedHttpsBackendRedirector.php(55): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #27 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #28 \\typo3\\sysext\\backend\\Classes\\Middleware\\LockedBackendGuard.php(73): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #29 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #30 \\typo3\\sysext\\core\\Classes\\Middleware\\NormalizedParamsAttribute.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #31 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
  #32 \\typo3\\sysext\\core\\Classes\\Http\\MiddlewareDispatcher.php(78): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #33 \\typo3\\sysext\\core\\Classes\\Http\\AbstractApplication.php(85): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #34 \\typo3\\sysext\\backend\\Classes\\Http\\Application.php(63): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #35 \\typo3\\sysext\\core\\Classes\\Http\\AbstractApplication.php(97): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
  #36 \\typo3\\index.php(25): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
  #37 \\typo3\\index.php(26): {closure}()
  #38 {main}"}
```
My extension is https://github.com/DavidBruchmann/wdb_news_snapin and comes with some data too, it's enough to create somewhere a news-record and in tab extra play a bit around with the options and trying to save then. Also install-tool and extension-manager break.
This behavior is in TYPO3 Versions 9 and 10,  `dev-master` is at least functional compatible to version 10.

**Comment by DavidBruchmann** [comment]
I created an issue about this on forge related to the core:
https://forge.typo3.org/issues/91773

**Comment by DavidBruchmann** [comment]
For this error was neither news nor the core responsible but an incomplete extension-update:
https://wiki.typo3.org/Exception/CMS/1596980032
